### PR TITLE
Synthetic data example: rainbow

### PR DESCRIPTION
**Pull request by sorrge**
Hi,

I've polished a bit the example I made as a test. It is now more impressive, showing quite good generalization from just 10% of the training data. The DALL-E training time is also reduced from original 4 hours to ~4 minutes. VAE still takes ~40 minutes to train.

I think it's a good starting point for people to explore your code, being a complete working example with no need to download data or train for days.

In addition, you can use it as a kind of regression test and to see if new features (e.g. sparse attention or other improvements) are at least able to solve this basic task.

So, hopefully useful.

### CODE REVIEW

**Comment by lucidrains** [comment]
@sorrge this is awesome! thank you!

**Comment by glencoe2004** [comment]
How do I use this? I'm running it through Anaconda, but I keep getting an `TypeError: forward() got an unexpected keyword argument 'return_recon_loss'` error that I can't seem to get past.

I am fairly new to using Anaconda and Jupyter though, so this is probably a mistake of my own doing.

**Comment by sorrge** [comment]
No, it's my mistake - from an older version of this repo. Please replace `return_recon_loss` with `return_loss`.

**Comment by glencoe2004** [comment]
Alright, now I'm getting `RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu`. Any ideas?

**Comment by sorrge** [comment]
I don't have that error. That seems related to a constructor in pytorch. Maybe we are using different versions of pytorch? Can you do `print(torch.__version__)`?

However, I don't even use torch.FloatTensor() anywhere. Does it give you stack trace with the error?

**Comment by glencoe2004** [comment]
According to `print(torch.__version__)`, I'm running version 1.7.1. Does DALLE support CUDA? I believe I may have installed pytorch with CUDA, so it might be breaking the program.

**Comment by sorrge** [comment]
Yes, this repo supports CUDA. In fact, the notebook requires it. You pytorch version is the same as mine.

I see now what the problem is in the DALLE-pytorch library. That line where the error originates doesn't exist in the latest version (from ~10 hour ago). Please do a git pull and reinstall the library, then the error should go away.

**Pull request merged**
