### PR TITLE
Fixes for the rainbow example

### PR DESCRIPTION
**Pull request by sorrge**
Sorry, @glencoe2004 found a bug, and then I found another. It's working now.

### CODE REVIEW

**Comment by lucidrains** [comment]
@sorrge i'll try to port it over to a colab notebook tomorrow!

**Comment by glencoe2004** [comment]
Alright, I think I've found another error:

By default, the 8th step will throw out an error about not being able to find any CUDA enabled devices. However, setting `["CUDA_VISIBLE_DEVICES"]` to 0 will fix the error (I think, my Notebook is still busy after running that step. At least it's gotten farther than before).

**Comment by sorrge** [comment]
Ah, sorry... For my GPU setup I had to run it on GPU #1. Now after you removed that line or set it to 0, it should work this time. I hope.

**Comment by glencoe2004** [comment]
Yeah I have no idea what happened, but trying to train multiple times just gets me this:

failed1

trainingstats1

**Comment by sorrge** [comment]
Are these just VAE reconstructions? Looks like it's failed. Never happened to me.

Just before showing this, it shows a matrix of VAE codes, like this:
```
tensor([[185, 193,  88, 185,  66,  66,  66, 185,  66,  66,  66, 193, 185,  66,
          88, 178],
        [193, 193,  66, 193, 123, 123, 123, 123, 198,  86,  86, 198, 191,  88,
          88, 109],
```
Can you post that too?

**Comment by glencoe2004** [comment]
Sure, here ya go:


```
tensor([[ 53, 190,  33, 243, 190,  53, 190, 243,  53, 234,  90, 243, 209,  89,
         243, 243],
        [ 53, 243, 243, 234,  72, 234, 254,  72, 224, 243,  72, 190, 234, 234,
         243, 190],
        [254, 190, 190,   4, 254,  53,  53, 243,  53,  53,  53, 243, 205, 216,
          89, 243],
        [243, 243, 243, 234, 234, 243, 243, 243, 243, 190, 181,  72,  72,  53,
         243, 190],
        [ 53, 190,  72, 234,  62, 254, 243, 234, 243, 243, 243, 243, 243, 243,
         234,  72],
        [ 53, 243,  53, 234, 243, 243, 243,  33, 243, 205, 243, 234, 243, 234,
          72,  72],
        [243, 243, 243, 234, 243, 243,  72, 234, 234, 234, 243, 234, 243, 224,
         234,  72],
        [243,  53, 243, 234, 243,  53, 243,  33,  33, 243, 243,  33,  53,  72,
         243,  72],
        [190, 181,  53, 243, 243, 243, 243, 190, 234, 234,  72, 243, 243, 243,
         243, 243],
        [243,  72, 243, 243, 243,  72, 234, 234, 243, 243, 243, 243, 243, 243,
         224, 243]], device='cuda:0')
```

**Comment by sorrge** [comment]
Thanks!

The codes look somewhat more repetitive than what I have, but generally ok. Reconstructions are completely bogus, though - they look like the average over the whole dataset. This could be a new bug. Maybe let's wait for @lucidrains to put it on Colab, where we can easily reproduce things.

**Comment by snoop2head** [comment]
I've added few fixes on #391 🤗
It also includes result ran on colab notebook, so hope it helps!

**Pull request merged**
