### PR TITLE
default Tokenizer is needed 

### PR DESCRIPTION
**Pull request by Napkin-DL**
If the bpe_path is None or chinese is false, then it doesn't have any tokenizer.

### CODE REVIEW

**Comment by lucidrains** [comment]
@Napkin-DL it is actually already pre-initialized here https://github.com/lucidrains/DALLE-pytorch/blob/main/dalle_pytorch/tokenizer.py#L154

**Comment by Napkin-DL** [comment]
@lucidrains However, the error occurred here https://github.com/lucidrains/DALLE-pytorch/blob/c4330e35d96708328bbe54a4ae8f6355056755a7/train_dalle.py#L203 when bpe_path and chiness were false.

**Comment by lucidrains** [comment]
@Napkin-DL can you show me your full command? it works for me

**Comment by Napkin-DL** [comment]
Sorry. I revised your code as a type of def main():  with if __name__ == "__main__": 
So, the main function didn't receive the tokenizer in from dalle_pytorch.tokenizer import tokenizer. I understood what was wrong.

**Pull request closed without merging**
