### PR TITLE
(deepspeed/wds) - patch dummy __len__ on wds dataset

### PR DESCRIPTION
**Pull request by afiaka87**

### CODE REVIEW

**Comment by afiaka87** [comment]
@robvanvolt @lucidrains @rom1504 this "fixes" the issue described https://github.com/lucidrains/DALLE-pytorch/issues/359

Are there likely to be issues with e.g. schedulers if the length returned here is smaller or larger than the actual length of a given epoch?

**Comment by afiaka87** [comment]
thanks @janEbert

**Comment by janEbert** [comment]
Thank you too! This would probably have been the only option in case the other solution didn't exist. :)

**Comment by lucidrains** [comment]
@afiaka87 thanks for this PR Clay!

**Comment by JingyunLiang** [comment]
After using this hacked __len__, I meet some errors as below:
```
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__                                 
    super().__init__(process_obj)                                                                                                                                  
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/multiprocessing/popen_fork.py", line 19, in __init__                                         
    self._launch(process_obj)                                                                                                                                        
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch                                  
    reduction.dump(process_obj, fp)                                                                                                                                  
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/multiprocessing/reduction.py", line 60, in dump                                              
    ForkingPickler(file, protocol).dump(obj)                                                                                                                         
AttributeError: Can't pickle local object 'BaseWebDataset.<locals>.patch_iterable_dataset_len.<locals>.
```
Anyone has a hint?

**Pull request closed without merging**
