### PR TITLE
Sample per sec

### PR DESCRIPTION
**Pull request by rom1504**
add sample per sec metric

### CODE REVIEW

**Comment by lucidrains** [comment]
@rom1504 Hey! I think if you dig into the weights and biases settings, they have that measure somewhere

**Comment by rom1504** [comment]
I looked but I'm not seeing it.
With that PR, I get a graph looking like this:
image
Which I think is pretty convenient when experimenting with settings affecting speed (batch size, deepspeed, fp16, depth)

**Comment by rom1504** [comment]
I rebased this on main.
Do you think this could make sense ?
It was convenient for me when measuring speed

**Comment by LukasKapp-Schwoerer** [comment]
This PR looks super useful to me and the code change is minimal, thanks for making it!

**Pull request merged**
