### PR TITLE
Clean up VRAM to allow for running on 8xV100

### PR DESCRIPTION
**Pull request by afiaka87**
I found that the rank 0 gpu needs to have its cache emptied or it will OOM on more than 4 GPUs in the same instance. This fixes that to a degree - although I'm still working on making sure each of the 8 GPU's is being used effectively - as it stands they can only get to about 10GiB/16GiB vram usage with a batch size of 64 (depth 8, heads 8, attn_types=('sparse'), reversible=False). But this should help at least.

### CODE REVIEW

**Comment by afiaka87** [comment]
I added calls to clean up the cache before initialization on _all_ GPUs as well - they may not be needed however.

**Comment by afiaka87** [comment]
@janEbert As discussed in the discord.

**Comment by afiaka87** [comment]
This also helps a lot on 4xV100 instances as well

**Comment by lucidrains** [comment]
@afiaka87 thanks for this! man, you and @janEbert are on a roll

**Comment by afiaka87** [comment]
Thanks @lucidrains! That means a lot.

**Pull request merged**
