### PR TITLE
fix memory issues for sparse convolutional attention

### PR DESCRIPTION
**Pull request by lucidrains**
https://github.com/lucidrains/DALLE-pytorch/issues/213

### CODE REVIEW

**Comment by lucidrains** [comment]
@afiaka87 do you want to try out this branch and see if it fixes memory issues for the `conv_like` attention? if it worked, i'll proceed and fix the axial ones too

**Comment by lucidrains** [comment]
@afiaka87 I went ahead and did the sparse axial too, let me know if it works!

**Comment by afiaka87** [comment]
> @afiaka87 I went ahead and did the sparse axial too, let me know if it works!

Just now getting started today - I'll have a look in a minute.

**Comment by afiaka87** [comment]
@lucidrains These are the benchmarks I'm getting currently - looks good but I can't test higher than the default low parameters. Yesterday I was getting OOM errors no matter what I did - today it seems they all use the same memory regardless? Perhaps due to reversible? At any rate - so far so good. 

('full', 'conv_like') - 4443M
('full', 'axial_row') - 4447M
('full', 'axial_col') - 4447M
('full', 'conv_like') - 4443M

('full', 'axial_col', 'axial_row', 'conv_like') - 4447M
('full', 'sparse') - 4447M (faster though)

**Comment by lucidrains** [comment]
thanks! your word is good enough :)

**Pull request merged**
