### PR TITLE
Fix some DeepSpeed issues

### LINKED ISSUE #141: Deepspeed Breaks Trying to Write to the Same Files
The current train_dalle.py will attempt to read/write to/from the same pretrained model checkpoints if they haven't been cached yet.
```bash
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
100%|████████████████████████| 215185363/215185363 [00:21<00:00, 9883569.70it/s]
Traceback (most recent call last):
  File "train_dalle.py", line 109, in <module>
    vae = vae_klass()
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 83, in __init__
    self.enc = load_model(download(OPENAI_VAE_ENCODER_PATH))
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 74, in download
    os.rename(download_target_tmp, download_target)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
100%|████████████████████████| 215185363/215185363 [00:22<00:00, 9738539.45it/s]
Traceback (most recent call last):
  File "train_dalle.py", line 109, in <module>
    vae = vae_klass()
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 83, in __init__
    self.enc = load_model(download(OPENAI_VAE_ENCODER_PATH))
  File "/root/DALLE-pytorch/dalle_pytorch/vae.py", line 74, in download
    os.rename(download_target_tmp, download_target)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/dalle/tmp.encoder.pkl' -> '/root/.cache/dalle/encoder.pkl'
 88%|█████████████████████▏  | 189546496/215185363 [00:22<00:07, 3572270.67it/s]Killing subprocess 2749
Killing subprocess 2750
Killing subprocess 2751
Killing subprocess 2752
Killing subprocess 2753
Killing subprocess 2754
Killing subprocess 2756
Killing subprocess 2758
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 171, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 161, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 139, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'train_dalle.py', '--local_rank=7', '--image_text_folder', '/root/output/', '--deepspeed']' returned non-zero exit status 1.
```

For now, to get it working, just run without deepspeed using python and cancel the program after the downloads are finished.

As for a long term solution - I assume deepspeed has a way to mark code as meant to run only once? Perhaps it could just be pinned to the GPU with 0 rank?

### LINKED ISSUE #142: Deepspead breaks if user hasnt logged in to wandb yet

### LINKED ISSUE #143: Deepspeed breaks if BATCH_SIZE less than number of GPUs
This one makes sense. We should probably either up the default batch size from 4 (i had this problem on an 8 GPU instance) or put an assertion about the batch_size in relation to the number of GPUs.

### PR DESCRIPTION
**Pull request by janEbert**
Improve the API, prevent concurrent I/O, only log from one process, fix some small mistakes.

Sadly, `torch.distributed.barrier` does not prevent concurrent I/O from multiple nodes. I was not able to find a better API inside DeepSpeed for now.

Also, when the user is not logged in to WandB, _only_ the root process crashes, so the other processes will continue and block. We could put a barrier after the WandB login to prevent the code from running further but again I haven't yet figured out how to cleanly exit from all processes.

Partly fix #141, partly fix #142, fix #143

### CODE REVIEW

**Comment by lucidrains** [comment]
@janEbert no worries, I'll just stub out the wandb with a mock that noops later today

thank you for all this!

**Comment by afiaka87** [comment]
> @lucidrains I'd like to test these changes out on a GPU instance before merge - just so we dont suffer from "works on my machine" syndrome.
> 
> @janEbert shoot me a ping when you feel it's ready for a test run on my end.

@lucidrains ...

**Comment by lucidrains** [comment]
i know what i'm doing ;)

**Comment by afiaka87** [comment]
Har har.

**Pull request merged**
